### ISSUE TITLE
Wrong 'memset' usage in fsr2GetPermutationBlobByIndex

### ISSUE THREAD

**Issue by FlyAndNotDown** [GPUOpen-Effects/FidelityFX-FSR2#41] opened 2022-07-29 11:05 UTC
See func `fsr2GetPermutationBlobByIndex`, there is a wrong usage of `memset`:

```cpp
FfxErrorCode fsr2GetPermutationBlobByIndex(
    FfxFsr2Pass passId,
    uint32_t permutationOptions,
    Fsr2ShaderBlobDX12* outBlob) {

    // ....

    // return an empty blob
    memset(&outBlob, 0, sizeof(Fsr2ShaderBlobDX12));
    return FFX_OK;
}
```

`outBlob ` is a pointer of `Fsr2ShaderBlobDX12`, but when use `memset` to reset memory, picked its pointer again, which will cause undefined behavior maybe ?

**Comment by FlyAndNotDown** [comment] 2022-07-29 11:11
There is a PR already, see #40

**Comment by rys** [comment] 2022-08-03 14:44
Closing, dupe of #40

**Closed by rys** 2022-08-03 14:44 UTC
